# Generated by Django 3.2.13 on 2022-04-18 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('general', '일반'), ('account', '계정'), ('etc', '기타')], default='general', max_length=15, verbose_name='카테고리')),
                ('title', models.TextField(verbose_name='제목')),
                ('email', models.CharField(max_length=320, verbose_name='이메일')),
                ('phone_number', models.CharField(max_length=11, verbose_name='전화번호')),
                ('content', models.TextField(verbose_name='내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='이미지')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='답변 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='답변 작성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 수정일시')),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.inquiry', verbose_name='참조 문의글 번호')),
                ('updater', models.ManyToManyField(blank=True, null=True, related_name='updated_answers', to=settings.AUTH_USER_MODEL, verbose_name='최종 수정자')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='답변 작성자')),
            ],
        ),
    ]
