# Generated by Django 3.2.13 on 2022-04-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_answer_updater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='phone_number',
            field=models.CharField(max_length=13, verbose_name='전화번호'),
        ),
    ]
