# Generated by Django 3.2.13 on 2022-04-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_faq_updater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='updater',
            field=models.CharField(default='작성자와 동일', max_length=255, verbose_name='최종 수정자'),
        ),
    ]
