# Generated by Django 3.2.13 on 2022-04-18 16:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0004_auto_20220418_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='updater',
            field=models.ManyToManyField(blank=True, null=True, related_name='updated_posts', to=settings.AUTH_USER_MODEL, verbose_name='최종 수정자'),
        ),
    ]
